spring:
  application:
    name: DoctorService
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true

server:
  port: ${portno:8181}
  
eureka: 
  client:  
    serviceUrl: 
       defaultZone: ${EUREKA_URI:http://eureka:9090/eureka/}
  instance:
    hostname: eureka
    prefer-ip-address: true