server:
  port: 9696
  
spring:
  application:
    name: API-GATEWAY-ZUUL
    
eureka: 
  client: 
    serviceUrl: 
       defaultZone: ${EUREKA_URI:http://localhost:9090/eureka/}
    register-with-eureka: false
    fetch-registry: false
  instance: 
    prefer-ip-address: true
    home-page-url: http://localhost:9090/
    
zuul:
  prefix: /api
  routes:
    DoctorService:
       path: /all
       service-id: DoctorService
       
ribbon:
  eureka:
    enabled: false      
       
DoctorService: 
  ribbon:
    listOfServers: http://localhost:8181,http://localhost:8182       