//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.11.01 at 10:38:12 AM IST 
//

package com.nit.bindings;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for anonymous complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="fname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="lname" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "fname", "lname" })
@XmlRootElement(name = "person")
public class Person {

	@XmlElement(required = true)
	protected String fname;
	@XmlElement(required = true)
	protected String lname;

	/**
	 * Gets the value of the fname property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getFname() {
		return fname;
	}

	/**
	 * Sets the value of the fname property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setFname(String value) {
		this.fname = value;
	}

	/**
	 * Gets the value of the lname property.
	 * 
	 * @return possible object is {@link String }
	 * 
	 */
	public String getLname() {
		return lname;
	}

	/**
	 * Sets the value of the lname property.
	 * 
	 * @param value allowed object is {@link String }
	 * 
	 */
	public void setLname(String value) {
		this.lname = value;
	}

}
