spring: 
 application:
    name: Accounts-Service-Swagger
 jpa:
    hibernate:
      ddl-auto: none 

    
server:
  port: 9001
  
eureka: 
  client: 
   register-with-eureka: false
   fetch-registry: false
   serviceUrl: 
       defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true