spring:
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
logging:
  file:
    name: D:\\Training\\SpringBoot-MicroServices\\logs\\SB-Customer-App.log
  level:
    org:
      springframework: ERROR
    com:
      nit:
        service: INFO